name: cfps
channels:
  - r
  - pytorch
dependencies:
  - jupyter
  - pip
  - python=2.7
  - numpy=1.14.*
  - matplotlib>=2.0
  - scikit-learn=0.19.*
  - pytorch=0.3.*
  - pandas>=0.22.*
  - r-base
  - rpy2>=2.8.6
  - pip:
    - dcor
    - pomegranate
  - networkx>=2.1


